services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
      args:
        host_uid: ${HOST_UID:-1000}
    ports:
      - '8080:8080'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  shop-service:
    build:
      context: .
      dockerfile: shop-service/Dockerfile
      args:
        host_uid: ${HOST_UID:-1000}
    ports:
      - '8081:8080'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  cart-service:
    build:
      context: .
      dockerfile: cart-service/Dockerfile
      args:
        host_uid: ${HOST_UID:-1000}
    ports:
      - '8082:8080'
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    ports:
      - '8000:8080'
    volumes:
      - ./openapi-spec.yaml:/openapi-spec.yaml
    environment:
      - SWAGGER_JSON=/openapi-spec.yaml
